version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4.0-debian-11-r0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - mysql

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - mysql

  notification-service:
    build: ./notification-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka

volumes:
  mysql_data:
